[build]
  publish = "public"
  functions = "func"
  command = "npm run build && node dist/build.js"

[build.environment]
  NODE_VERSION = "16.15.0"

[build.processing]
  css = { bundle = true, minify = true }
  js = { minify = true }
  html = { pretty_urls = true }
  images = { compress = true }

[functions]
  node_bundler = "esbuild"

[functions.fetch]
  external_node_modules = ["undici"]

[template.environment]
  DISCORD_CLIENT_ID = "Your Discord App's client ID"
  DISCORD_CLIENT_SECRET = "Your Discord App's client secret"
  DISCORD_TOKEN = "Your Discord Bot Token"
  GUILD_ID = "ID of the guild this deployment targets"
  APPEALS_CHANNEL = "ID of the channel used for appeal form submission"
  JWT_SECRET = "JSON Web Token secret, mash keyboard plz"