[build]
  publish = "public"
  functions = "func"
  command = "npm run start"

[build.environment]
  NODE_VERSION = "17.9.0"

[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = false
  minify = false
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

[functions]
  node_bundler = "esbuild"

[template.environment]
  DISCORD_CLIENT_ID = "Your Discord App's client ID"
  DISCORD_CLIENT_SECRET = "Your Discord App's client secret"
  DISCORD_TOKEN = "Your Discord Bot Token"
  GUILD_ID = "ID of the guild this deployment targets"
  APPEALS_CHANNEL = "ID of the channel used for appeal form submission"
  JWT_SECRET = "JSON Web Token secret, mash keyboard plz"